name: Deploy on LocalStack 

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # “At 00:00 on Sunday.”
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sam:
    name: Setup infrastructure using SAM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Install lstk
        run: npm install -g @localstack/lstk

      - name: Start LocalStack
        run: |
          docker pull localstack/localstack-pro:latest
          # Start LocalStack in the background
          LOCALSTACK_DEBUG=1 lstk start
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      - name: Build the Lambda Layer 
        run: |
          cd function
          pip install --target ../package/python -r requirements.txt

      - name: Build the SAM app
        run: |
          lstk sam build

      - name: Deploy the SAM app
        run: |
          curl http://localhost:4566/_localstack/info
          lstk sam deploy --no-confirm-changeset
