name: Deploy on LocalStack 

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # “At 00:00 on Sunday.”
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sam:
    name: Setup infrastructure using SAM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: gautamkrishnar/keepalive-workflow@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Setup SAM-Local 
        run: |
          pip install aws-sam-cli-local
          samlocal --help

      - name: Start LocalStack
        run: |
          pip install localstack
          docker pull localstack/localstack-pro:latest
          # Start LocalStack in the background
          DEBUG=1 localstack start -d
          # Wait 30 seconds for the LocalStack container to become ready before timing out
          echo "Waiting for LocalStack startup..."
          localstack wait -t 15
          echo "Startup complete"
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

      - name: Build the Lambda Layer 
        run: |
          cd function
          pip install --target ../package/python -r requirements.txt

      - name: Build the SAM app 
        run: |
          samlocal build 

      - name: Deploy the SAM app
        run: |
          curl http://localhost:4566/_localstack/info
          samlocal deploy --no-confirm-changeset
  